### ISSUE TITLE
Gar kein Output

### ISSUE THREAD

**Issue by cukabeka** [olien/das_modul#18]
Weiß nicht, ob das evtl am aktuellen Entwicklungsstatus liegt, aber bei mir wird weder im Backend noch im Frontend der Content ausgegeben. Editieren funktioniert.

**Comment by olien** [comment]
Ich weiß nicht wie Du testest und grad auch nicht wie der Entwicklungsstand ist.
Wir arbeiten an einer verbesserten Version :-)
Dauert noch etwas.

LG
Oliver
